In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp
import astropy as ap
import ugradio


%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [ ]:
ugradio.pico.capture_data?

In [ ]:
ugradio.pico.VOLT_RANGE

In [2]:
from collect_data import collect_data

In [40]:
collect_data('100mV', 1)
# a, b, c = plt.hist(collect_data('100mV', 1.)[0])
# a, b, c = plt.hist(collect_data('100mV', 1.)[1])

[array([ 256,  256,  256, ..., -768, -256,    0], dtype=int16),
 array([  256, -1024,     0, ...,   768,   768,   256], dtype=int16)]

In [13]:
np.fft.fft(collect_data('100mV', 1)[0])

array([ 1550336.00000000    +0.j        ,
         -46142.17826396-41685.05620446j,
         -16858.97393277-64252.48332423j, ...,
          84639.48354794-60348.05808268j,
         -16858.97393277+64252.48332423j,   -46142.17826396+41685.05620446j])

In [ ]:
# collect_data('6_2_1_50mV_1', '50mV', 1)

A = 0.05*np.genfromtxt('6_2_1_50mV_1_A')/2.**15
B = 0.05*np.genfromtxt('6_2_1_50mV_1_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
# collect_data('6_2_1_100mV_1', '100mV', 1)

A = 0.1*np.genfromtxt('6_2_1_100mV_1_A')/2.**15
B = 0.1*np.genfromtxt('6_2_1_100mV_1_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
# collect_data('6_2_1_50mV_2', '50mV', 2)

A = 0.5*np.genfromtxt('6_2_1_50mV_2_A')/2.**15
B = 0.5*np.genfromtxt('6_2_1_50mV_2_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
# collect_data('6_2_1_100mV_2', '100mV', 2)

A = 0.5*np.genfromtxt('6_2_1_100mV_2_A')/2.**15
B = 0.5*np.genfromtxt('6_2_1_100mV_2_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
# collect_data('6_2_1_50mV_5', '50mV', 5)

A = 0.5*np.genfromtxt('6_2_1_50mV_5_A')/2.**15
B = 0.5*np.genfromtxt('6_2_1_50mV_5_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
# collect_data('6_2_1_100mV_5', '100mV', 5)

A = 0.5*np.genfromtxt('6_2_1_100mV_5_A')/2.**15
B = 0.5*np.genfromtxt('6_2_1_100mV_5_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
collect_data?

In [ ]:
# collect_data('6_2_3_50mV_1', '50mV', 1)

A = 0.5*np.genfromtxt('6_2_3_50mV_1_A')/2.**15
B = 0.5*np.genfromtxt('6_2_3_50mV_1_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:256], label = 'A')
plt.plot(B[:256], label = 'B')
plt.legend()

In [ ]:
# collect_data('6_2_3_50mV_2', '50mV', 2)
N = 256
vsamp = 62.5/2
time = np.arange(-N/2/vsamp, (N/2. - 1)/vsamp)

A = 0.5*np.genfromtxt('6_2_3_50mV_2_A')/2.**15
B = 0.5*np.genfromtxt('6_2_3_50mV_2_B')/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(A[:N], label = 'A')
plt.plot(B[:N], label = 'B')
plt.legend()

plt.figure()
plt.plot(np.fft.fft(A).real)
# plt.plot(np.fft.fft(A).imag)

plt.figure()
plt.plot(np.fft.fftfreq(len(A)), abs(np.fft.fft(A))**2)

In [ ]:
# collect_data('6_2_3_50mV_5', '50mV', 5)
N = 512
vsamp = 62.5/5
time = np.linspace(-N/2./vsamp, (N/2. - 1)/vsamp,N)
freq = np.linspace(-vsamp/2, (vsamp/2)*(1-2./N),N)

A = 0.5*np.genfromtxt('6_2_3_50mV_5_A')[:N]/2.**15
B = 0.5*np.genfromtxt('6_2_3_50mV_5_B')[:N]/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(time, A, label = 'A')
plt.plot(time, B, label = 'B')
plt.legend()

plt.figure()
plt.plot(freq, np.fft.fft(A).real)
# plt.plot(np.fft.fft(A).imag)

plt.figure()
plt.plot(freq, abs(np.fft.fft(A))**2)
# plt.plot(np.fft.fftfreq(len(B)), abs(np.fft.fft(B))**2)

In [ ]:
d = 10
# collect_data('6_2_3_50mV_10', '50mV', d)
N = 512
vsamp = 62.5/d
time = np.linspace(-N/2./vsamp, (N/2. - 1)/vsamp,N)
freq = np.linspace(-vsamp/2, (vsamp/2)*(1-2./N),N)

A = 0.5*np.genfromtxt('6_2_3_50mV_10_A')[:N]/2.**15
B = 0.5*np.genfromtxt('6_2_3_50mV_10_B')[:N]/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(time, A, label = 'A')
plt.plot(time, B, label = 'B')
plt.legend()

plt.figure()
plt.plot(freq, np.fft.fft(A).real)
# plt.plot(np.fft.fft(A).imag)

plt.figure()
plt.plot(freq, abs(np.fft.fft(A))**2)
# plt.plot(np.fft.fftfreq(len(B)), abs(np.fft.fft(B))**2)

In [ ]:
d = 13
# collect_data('6_2_3_50mV_13', '50mV', d)
N = 512
vsamp = 62.5/d
time = np.linspace(-N/2./vsamp, (N/2. - 1)/vsamp,N)
freq = np.linspace(-vsamp/2, (vsamp/2)*(1-2./N),N)

A = 0.5*np.genfromtxt('6_2_3_50mV_13_A')[:N]/2.**15
B = 0.5*np.genfromtxt('6_2_3_50mV_13_B')[:N]/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(time, A, label = 'A')
plt.plot(time, B, label = 'B')
plt.legend()

plt.figure()
plt.plot(freq, np.fft.fft(A).real)
# plt.plot(np.fft.fft(A).imag)

plt.figure()
plt.plot(freq, abs(np.fft.fft(A))**2)
# plt.plot(np.fft.fftfreq(len(B)), abs(np.fft.fft(B))**2)

In [ ]:
# test is now 1422 instead of 1421
d = 13
# collect_data('test_6_2_3_50mV_13', '50mV', d)
N = 512
vsamp = 62.5/d
time = np.linspace((-N/2.)/vsamp, (N/2. - 1)/vsamp,N)
freq = np.linspace(-vsamp/2, (vsamp/2)*(1-2./N),N)

A = 0.5*np.genfromtxt('test_6_2_3_50mV_13_A')[:N]/2.**15
B = 0.5*np.genfromtxt('test_6_2_3_50mV_13_B')[:N]/2.**15

n, bins, edges = plt.hist(A, bins = 20, alpha = 0.5, label = 'A')
n, bins, edges = plt.hist(B, bins = 20, alpha = 0.5, label = 'B')
plt.legend()

plt.figure()
plt.plot(time, A, label = 'A')
plt.plot(time, B, label = 'B')
plt.legend()

plt.figure()
plt.plot(freq, np.fft.fft(A).real)
# plt.plot(np.fft.fft(A).imag)

plt.figure()
plt.plot(freq, abs(np.fft.fft(A))**2)
# plt.plot(np.fft.fftfreq(len(B)), abs(np.fft.fft(B))**2)

In [ ]:
not isinstance(True, ndarray)

type(np.linspace(0,5,3))

In [22]:
len(ugradio.pico.capture_data('50mV', 1, nblocks=5))

80000

In [18]:
d = 2
# collect_data('test_6_2_3_50mV_13', '50mV', d)
N = 512
vsamp = 62.5/d
time = np.linspace((-N/2.)/vsamp, (N/2. - 1)/vsamp,N)
freq = np.linspace(-vsamp/2, (vsamp/2)*(1-2./N),N)


make_complex('50mV', 2)

(array([-256,  512,  512, ...,  256,    0,    0], dtype=int16),
 array([-512,    0,    0, ...,  768,  256,    0], dtype=int16),
 [(-256-512j),
  (512+0j),
  (512+0j),
  (256+0j),
  (512+512j),
  (768+768j),
  (768+512j),
  (-256+0j),
  (-512+512j),
  (-256+1024j),
  (-768+768j),
  (512+512j),
  (-512-256j),
  0j,
  (512+256j),
  (768+256j),
  (512+0j),
  512j,
  768j,
  (512+256j),
  0j,
  (256+0j),
  (512+768j),
  (512+0j),
  (256+0j),
  -256j,
  (1024+0j),
  (256+0j),
  0j,
  0j,
  (256-256j),
  (256-256j),
  (768-256j),
  (512+0j),
  (256+0j),
  (512+0j),
  (512+768j),
  (1024-256j),
  (256-256j),
  (512+256j),
  (768+0j),
  (768+256j),
  (768+256j),
  (1024+1024j),
  (1280+1024j),
  (768+1024j),
  512j,
  (-256+1280j),
  512j,
  (1024-256j),
  (256+512j),
  (768+1024j),
  (768+1280j),
  1024j,
  (256+1024j),
  (256+1280j),
  (512+768j),
  512j,
  512j,
  (256+1024j),
  512j,
  (512-256j),
  512j,
  (256+1024j),
  768j,
  (-512+768j),
  (256+512j),
  (256+512j),
  (256+256j),
  (-25

In [23]:
x = np.array([1,2,3,4])

In [16]:
def make_complex(v, div, arrA = True, arrB = True, dualmode = True, nbloc = 1, nsamp = 16000, fileName = 'data_test', saveFile = False):
    ll = collect_data(v, div, dualmode, nbloc, nsamp, fileName, saveFile )
    if not isinstance(arrA, ndarray):
        arrA = ll[0]
    if not isinstance(arrB, ndarray):
        arrB= ll[1]
    
    complex_num = []
    for a,b in zip(arrA,arrB):
        complex_num.append(a + 1j*b )
    return arrA, arrB, complex_num

# add save file argument

In [24]:
x

array([1, 2, 3, 4])

In [25]:
x % 2

array([1, 0, 1, 0])

In [26]:
real = np.array(x % 2, dtype = bool)

In [27]:
real

array([ True, False,  True, False], dtype=bool)

In [28]:
x[real]

array([1, 3])

In [29]:
x[np.invert(real)]

array([2, 4])

In [30]:
x[real] + 1j*x[np.invert(real)]

array([ 1.+2.j,  3.+4.j])

In [33]:
split = np.split(x, 2)

In [34]:
split

[array([1, 2]), array([3, 4])]

In [36]:
c = split[0] + 1j* split[1]

In [46]:
ugradio.pico.capture_data?

In [37]:
c

array([ 1.+3.j,  2.+4.j])

In [39]:
np.arange(0, 2 * 4) % 2

array([0, 1, 0, 1, 0, 1, 0, 1])

In [68]:
def make_complex(v, div, arrA = True, arrB = True, dualmode = True, nbloc = 1, nsamp = 16000, fileName = 'data_test', saveFile = False):
    ll = ugradio.pico.capture_data(v, divisor = div, dual_mode = dualmode, nsamples = nsamp, nblocks = nbloc)
    split = np.split(ll, 2*nbloc)
    return split

In [70]:
np.shape(make_complex('50mV', 2, nbloc = 1))

(2, 16000)

In [65]:
len(ugradio.pico.capture_data('50mV', divisor = 2, nblocks = 3, dual_mode = True))

96000

In [66]:
collect_data('100mV', 2, saveFile= True, fileName= 'good_data')

Saved A port data to good_data_A.txt
Saved B port data to good_data_B.txt


[array([ 1792,   768,  -512, ..., -3840, -4096, -3328], dtype=int16),
 array([-2048,  -768,   256, ...,  4352,  4096,     0], dtype=int16)]

In [67]:
collect_data('50mV', 2, saveFile = True, fileName = 'good_data1')

Saved A port data to good_data1_A.txt
Saved B port data to good_data1_B.txt


[array([6400, 7680, 8960, ..., 3840, 1024,    0], dtype=int16),
 array([ 3584,  1280,  -768, ..., -7424, -7424, -7168], dtype=int16)]

In [71]:
#1421 

collect_data('100mV', 1, saveFile = True, fileName = '1421_data')

Saved A port data to 1421_data_A.txt
Saved B port data to 1421_data_B.txt


[array([-1792, -3328, -3840, ..., -4352, -4864, -3584], dtype=int16),
 array([ -768, -2048, -2048, ..., -3840, -4352,     0], dtype=int16)]

In [72]:
np.savetxt('1421_5blocks' , ugradio.pico.capture_data('100mV', divisor = 1, dual_mode= True, nblocks= 5))

In [73]:
np.savetxt('notest_1420', ugradio.pico.capture_data('100mV', divisor = 1, dual_mode= True, nblocks= 5))

In [74]:
np.savetxt('1419_5blocks', ugradio.pico.capture_data('100mV', divisor = 1, dual_mode= True, nblocks= 5))

In [75]:
np.savetxt('1419_1block', ugradio.pico.capture_data('100mV', divisor = 1, dual_mode= True))